sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
  - 'npm install -g npm@latest' # need latest npm on 0.10 for scoped modules
  - 'npm install electron-prebuilt' # seemed weird to have it a devDep
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
script: 'npm run ci'
